network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:  # Replace 'enp0s3' with your network interface name
      addresses:
        - 192.168.1.100/24  # Replace with your desired static IP and subnet mask
      routes:
        - to: 0.0.0.0/0  # Default route
          via: 192.168.1.1  # Replace with your gateway IP
          on-link: true
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]  # Replace with your DNS server IPs